### ISSUE TITLE
First issue! Types are red, not aquamarine.

### ISSUE THREAD

**Issue by armarti** [notAlaanor/cppRecolored#1]
Thanks for your little extension.

[Here](https://github.com/notAlaanor/cppRecolored/blob/7f3458630f75f70d5f231d1a23fef6b9aca4be02/package.json#L82) the default color for types is a red color, but the default color for vscode (and the color of types on your extension page) is like aquamarine, which is #4ec9b0 (taken from vscode devtools).

**Comment by notAlaanor** [comment]
Hey, thanks for the issue.

Right now the VSCode API doesn't support programmatically finding the current theme colors, so I picked a red color to passively notify the user that they should probably change the color to match their theme. Per your suggestion, however, I changed the default color to `#4ec9b0` so it matches the default theme and made it more clear in the README.

If you have any other questions, let me know.
